### ISSUE TITLE
♫ Rien à cacher - Jérémie Zimmermann et la Parisienne Libérée (english spanish hungarian subtitles)

### ISSUE THREAD

**Issue by willdurand** [willdurand/jenairienacacher.fr#21]
https://www.youtube.com/watch?v=rEwf4sDgxHo

**Comment by mazenovi** [comment]
je pense qu'on devrait avant d'ajouter des ressources supplémentaires structurer les contenus en 3 familles
* les contenus statiques sous forme de pages (comme c'est déjà le cas)
  * index
  * transparence
  * surveillance
  * gratuite-publicite 
  * intelligence-economie à venir
* les ressources pertinentes, taguées ( transparence, surveillance, gratuite-publicite, intelligence-economie) sous forme de posts. chaque contenu statique affiche en pied de page les n dernières ressources associées à son tag
* une boite en page d'accueil ou dans une colonne à part sur toutes les pages qui reprend le fil de @rienacacher_fr
