### ISSUE TITLE
Vidéoprotection vs Vidéosurveillance

### ISSUE THREAD

**Issue by willdurand** [willdurand/jenairienacacher.fr#25]
> Est-ce qu'il ne serait pas plus opportun de remplacer ce terme par le terme original de vidéosurveillance partout où vous l'employez, avec une petite explication de ce piège sémantique quelque part ? Parler de "vidéoprotection", c'est déjà un peu donner une victoire idéologique à ceux qui veulent l'imposer, non ?

**Comment by mazenovi** [comment]
"A titre d'information le terme vidéosurveillance a été remplacé par le terme vidéoprotection dans la loi via la LOPPSI II en 2010." c'est dit clairement dans la partie "Les caméras de vidéoprotection" ce qui 1 - mentionne le piège sémantique et 2 - explique qu'en France désormais on parle de **vidéoprotection** et non plus de **vidéosurveillance**. Le lien "Videosurveillance - Videoprotection - Chronologie" dans la partie "Ressources supplémentaires" est là pour enfoncer le clou. Je suis pour fermer cette issue

**Comment by willdurand** [comment]
La réponse qui m'a été faite après avoir répondu de la sorte : 

> Certes, mais disons que même si "vidéoprotection" est devenu le terme officiel, ça reste un peu de la novlangue quand même, et un terme piège.

**Comment by mazenovi** [comment]
alors metionnons que **vidéoprotection** est un terme novlangue, mais le droit français ne concerne désormais plus la **vidéosurveillance** mais bien la **vidéoprotection**.
Un contre argument est que la cnil parle plutôt de **vidéosurveillance** http://www.cnil.fr/les-themes/videosurveillance/

**Comment by willdurand** [comment]
:+1:
