### ISSUE TITLE
Préférer privacybadger à ghostery

### ISSUE THREAD

**Issue by arthurlutz** [willdurand/jenairienacacher.fr#29]
Ghostery n'est pas un logiciel libre et dépend d'une entreprise qui vend des données aux publicitaires. Pour plus d'informations : http://surfezcouvert.net/?p=245

Recommander plutôt Privacy Badger https://www.eff.org/privacybadger de l'EFF https://www.eff.org à laquelle on peut faire plus confiance (et c'est du logiciel libre).

Idem si on part du coté adblock plus, recommander la version libre adblock edge https://addons.mozilla.org/en-US/firefox/addon/adblock-edge/ (sans la whiteliste sponsorisé qui finance la boite d'adblock plus).

**Comment by willdurand** [comment]
> Ghostery n'est pas un logiciel libre et dépend d'une entreprise qui vend des données aux publicitaires. Pour plus d'informations : http://surfezcouvert.net/?p=245
> Recommander plutôt Privacy Badger https://www.eff.org/privacybadger de l'EFF https://www.eff.org à laquelle on peut faire plus confiance (et c'est du logiciel libre).

Privacy Badger est intéressant, merci ! Pour autant, [l'EFF ne renie pas l'utilisation de Ghostery](https://www.eff.org/deeplinks/2013/07/how-opt-out-twitters-tailored-advertisements-and-more), et l'extension supporte **tous** les navigateurs, ce qui est un point important malgré tout (et [leurs conditions semblent correctes](https://www.ghostery.com/en/privacy-addon)).

> Idem si on part du coté adblock plus, recommander la version libre adblock edge https://addons.mozilla.org/en-US/firefox/addon/adblock-edge/ (sans la whiteliste sponsorisé qui finance la boite d'adblock plus).

Je suis tout à fait pour virer ABP qui n'est pas super transparent :+1:

Après, je partirais plutôt sur https://github.com/gorhill/uBlock (mais je ne connaissais pas Edge, merci encore !)

**Comment by arthurlutz** [comment]
Attention à la chronologie : en 2013 EFF "recommande" Ghostery car PrivacyBadger n'existait pas. Ce n'est peut-être pas sans lien et les critiques de Ghostery on peut-être débouché sur la création de PrivacyBadger. Je te laisse lire https://en.wikipedia.org/wiki/Ghostery#Criticism

**Comment by willdurand** [comment]
Merci, entre temps j'ai lu quelques liens par rapport à ça. Je pense qu'on peut privilégier PrivacyBadger (parce que les projets EFF sont très très biens) mais pas non plus crier trop sur Ghostery (si on désactive Ghostrank, ce qui est quand même transparent).

**Comment by arthurlutz** [comment]
Bienvenu aux questions (fondamentales) des options par défaut que personne ne change (cf les débats houleux sur DNT).

**Comment by willdurand** [comment]
Pour me faire l'avocat du diable (Ghostery) une seconde fois, lors de l'installation il y a toute une page d'explications demandant si l'on souhaite "activer" GhostTank (edit: on ne peut pas y échapper et c'est écrit clairement) :stuck_out_tongue:

**Comment by auzias** [comment]
Je suis d'accord avec @arthurlutz . Ghostery prétend protéger l'utiliser contre le tracking de l'utilisateur tout en faisant son fond de commerce. Les "moldus", pensant faire une bonne action, l'installent et, étant des "moldus", ne lisent pas "page d'explications" demandant s'ils souhaitent activer ceci ou cela.

Je pense qu'en discuter/le nommer pour un autre objectif que de dire "méfiez-vous en" sur ce projet serait .... "contre-productif".

**Comment by mazenovi** [comment]
:+1: pour PrivacyBadger
