### ISSUE TITLE
Mozilla: Gérez votre vie privée intelligemment

### ISSUE THREAD

**Issue by auzias** [willdurand/jenairienacacher.fr#30]
https://www.mozilla.org/fr/privacy/tips/
Une bonne ressource :+1: 

Bravo pour le projet sinon :) !

**Comment by willdurand** [comment]
En effet, on garde ça au chaud, merci !

_PS : On voulait d'abord mettre en avant : du contenu, des faits et sourcer le plus possible. L'idée d'ajouter des "outils" est venue ensuite et est complémentaire. L'important était de donner des infos sur ce non-argument. Faire prendre conscience que tout le monde a quelque chose à cacher **et** qu'ils devraient faire gaffe à leurs données, etc. sont **deux** points différents et complémentaires, **deux** missions différentes. Il faut y aller doucement avec les "moldus"_ :stuck_out_tongue:

**Comment by mazenovi** [comment]
https://www.mozilla.org/fr/lightbeam/ pourrait avoir sa place au côté de PrivacyBadger, il donne une bonne idéee de l'ampleur des tracing cookie au fil de la navigation
